version: 0.2

env:
  parameter-store:
      DOCKER_REGISTRY_USERNAME: /sudoku-solver/docker-credentials/username
      DOCKER_REGISTRY_PASSWORD: /sudoku-solver/docker-credentials/password
      DOCKER_REGISTRY_URL: /sudoku-solver/docker-credentials/registery_url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - pip install -r requirements.txt
      
  build:
    commands:
      - echo "Building Docker Image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sudoku-solver-cicd:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sudoku-solver-cicd:latest"
  
  
  post_build:
    commands:
      - echo "Build Successful"
      - echo "Currently in the Post Build Phase"
